// ═══════════════════════════════════════════════════════════════════════
// src/shared/services/aiStudyMaterialService.ts
// Frontend client for the AI Study Material Generator Agent
// ═══════════════════════════════════════════════════════════════════════

import { apiUrl, assertJsonResponse } from '@/shared/api/apiBase';

export interface KeyConceptItem {
  term: string;
  definition: string;
  formulaOrRule?: string;
  importance?: string;
}

export interface WorkedStep {
  step: string;
  details: string;
}

export interface WorkedExample {
  scenario: string;
  steps: WorkedStep[];
  solution: string;
}

export interface ExamPrepQuestion {
  question: string;
  expectedAnswer: string;
  marks: number;
  bloomLevel?: string;
  examTip?: string;
}

export interface AIStudyPack {
  title: string;
  subject: string;
  overview: string;
  quickSummaryPoints: string[];
  keyConcepts: KeyConceptItem[];
  workedExample: WorkedExample;
  examPrep: ExamPrepQuestion[];
}

export interface FetchStudyMaterialInput {
  subject: string;
  topic: string;
  courseName?: string;
  courseCode?: string;
  moduleName?: string;
  moduleNo?: number | string;
  branch?: string;
  semester?: number | string;
  forceRefresh?: boolean;
}

export interface FetchStudyMaterialResponse {
  success: boolean;
  source: 'cache' | 'generated';
  cachedAt?: string;
  cacheKey?: string;
  /** Immutable version that was served (versions never change once written). */
  servedVersion?: number;
  /** True when the served version came from this campus's own pin. */
  pinned?: boolean;
  data: AIStudyPack;
}

/** Progress ping while another caller's generation is in flight (HTTP 202). */
export interface StudyMaterialWaitInfo {
  attempt: number;
  retryAfterMs: number;
  cacheKey?: string;
}

/**
 * Matches the server: when a pack is being generated by someone else the
 * endpoint answers 202 and the winner's commit lands in well under a minute.
 * We poll politely instead of paying for a duplicate generation.
 */
const STUDY_MATERIAL_WAIT_BUDGET_MS = 150_000;

async function getBearerToken(): Promise<string | null> {
  const stored =
    localStorage.getItem('token') ||
    sessionStorage.getItem('token') ||
    localStorage.getItem('vriddhi_auth_token');
  if (stored) return stored;
  try {
    const { auth } = await import('@/Firebase/config');
    if (auth.currentUser) return await auth.currentUser.getIdToken();
  } catch {}
  return null;
}

async function authedFetch(endpoint: string, init: RequestInit): Promise<Response> {
  const token = await getBearerToken();
  const url = apiUrl(endpoint);
  const response = await fetch(url, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token || ''}`,
      ...(init.headers || {}),
    },
  });
  await assertJsonResponse(response, url);
  return response;
}

export async function fetchAIStudyMaterial(
  input: FetchStudyMaterialInput,
  opts?: { onWaiting?: (info: StudyMaterialWaitInfo) => void; maxWaitMs?: number }
): Promise<FetchStudyMaterialResponse> {
  const deadline = Date.now() + (opts?.maxWaitMs ?? STUDY_MATERIAL_WAIT_BUDGET_MS);
  let attempt = 0;
  // Once someone else is generating, polling as a PLAIN serve (never a
  // refresh) is what keeps "two staff pressing regenerate" a single paid call.
  let forceRefresh = input.forceRefresh === true;

  while (true) {
    const response = await authedFetch('/ai/study-material', {
      method: 'POST',
      body: JSON.stringify({ ...input, forceRefresh }),
    });
    const body = await response.json();

    if (body?.inProgress) {
      forceRefresh = false;
      attempt += 1;
      const retryAfterMs = Math.min(Math.max(Number(body.retryAfterMs) || 4000, 1500), 10_000);
      if (Date.now() + retryAfterMs > deadline) {
        throw new Error(
          'This study pack is still being generated. Open it again in a minute — it will load instantly from the shared cache.'
        );
      }
      opts?.onWaiting?.({ attempt, retryAfterMs, cacheKey: body.cacheKey });
      await new Promise((resolve) => setTimeout(resolve, retryAfterMs));
      continue;
    }
    return body as FetchStudyMaterialResponse;
  }
}

// ─── Staff pre-warm (bulk cache warming) ─────────────────────────────────

export interface PrewarmModuleInput {
  topic: string;
  moduleNo?: number | string;
  moduleName?: string;
}

export interface PrewarmModuleResult {
  topic: string;
  status: 'cached' | 'generated' | 'in-progress' | 'error' | 'limited' | string;
  version?: number;
}

export interface PrewarmProgress {
  processed: number;
  total: number;
  last?: PrewarmModuleResult;
}

export interface PrewarmSummary {
  results: PrewarmModuleResult[];
  done: boolean;
  /** Set when the run stopped early because a daily cap tripped. */
  limitedScope: 'student' | 'college' | null;
}

/**
 * Loops the server's batched pre-warm endpoint until every module is cached
 * (or a daily cap stops the run). Idempotent: re-running simply reports
 * everything as 'cached' and costs nothing.
 */
export async function prewarmAIStudyMaterials(
  input: {
    subject: string;
    courseName?: string;
    courseCode?: string;
    branch?: string;
    semester?: number | string;
    modules: PrewarmModuleInput[];
  },
  onProgress?: (progress: PrewarmProgress) => void
): Promise<PrewarmSummary> {
  const results: PrewarmModuleResult[] = [];
  let startIndex = 0;

  while (startIndex < input.modules.length) {
    const response = await authedFetch('/ai/study-material/prewarm', {
      method: 'POST',
      body: JSON.stringify({ ...input, startIndex }),
    });
    const body = await response.json();
    const batchResults = (body.results || []) as PrewarmModuleResult[];
    results.push(...batchResults);
    onProgress?.({
      processed: Math.min(Number(body.nextIndex) || input.modules.length, input.modules.length),
      total: input.modules.length,
      last: batchResults[batchResults.length - 1],
    });
    if (body.limited) {
      return { results, done: false, limitedScope: body.limited.scope || null };
    }
    const next = Number(body.nextIndex);
    if (!Number.isFinite(next) || next <= startIndex || body.done) break;
    startIndex = next;
  }
  return { results, done: true, limitedScope: null };
}

// ─── Cost controls (usage meter + limits + exam freeze windows) ──────────

export interface StudyFreezeWindow {
  start: string;
  end: string;
  reason?: string;
}

export interface StudyMaterialUsageCounters {
  serves: number;
  generations: number;
  tokensIn: number;
  tokensOut: number;
}

export interface StudyMaterialControls {
  success: boolean;
  date: string;
  collegeId: string | null;
  today: StudyMaterialUsageCounters;
  global?: StudyMaterialUsageCounters & {
    colleges: Record<string, Partial<StudyMaterialUsageCounters>>;
  };
  config: {
    studentDailyGenerationLimit: number;
    collegeDailyGenerationLimit: number;
    freezeWindows: StudyFreezeWindow[];
  };
  defaults: {
    studentDailyGenerationLimit: number;
    collegeDailyGenerationLimit: number;
  };
  freeze: { frozen: boolean; until?: string; reason?: string };
}

export async function getStudyMaterialControls(targetCollegeId?: string): Promise<StudyMaterialControls> {
  const query = targetCollegeId ? `?collegeId=${encodeURIComponent(targetCollegeId)}` : '';
  const response = await authedFetch(`/ai/study-material/controls${query}`, { method: 'GET' });
  return response.json();
}

export async function updateStudyMaterialControls(
  patch: {
    studentDailyGenerationLimit?: number;
    collegeDailyGenerationLimit?: number;
    freezeWindows?: StudyFreezeWindow[];
  },
  targetCollegeId?: string
): Promise<{ success: boolean; collegeId: string; config: StudyMaterialControls['config'] }> {
  const response = await authedFetch('/ai/study-material/controls', {
    method: 'PUT',
    body: JSON.stringify({ ...patch, ...(targetCollegeId ? { collegeId: targetCollegeId } : {}) }),
  });
  return response.json();
}
