// functions/src/routes/attendancePdf.ts
//
// `POST /attendance/register/pdf` — the server-rendered attendance register
// (item 4.3 of docs/HANDOFF_OPTIMISATION_2026-09-25.md).
//
// The browser sends the report it has already built (title, subtitle, sheets of
// headers + rows) and gets back a text PDF printed by Chrome. Nothing is read
// from Firestore here: the client has the data, has already applied the user's
// college/department scope, and the route only renders what it is given.
//
// That is deliberate, and it is also why this route can be replaced without a
// data migration later. What it must NOT become is a second place where
// attendance visibility rules live.
//
// Contract with the client (see src/shared/utils/serverReportPdf.ts): when the
// renderer is unavailable this answers 503 with `{ fallback: 'client' }`, and the
// browser draws the sheet itself with jsPDF — exactly as it does today. That
// fallback stays for one release after parity is confirmed.

import type { Response } from 'express'
import { logger } from 'firebase-functions'

import { AuthenticatedRequest } from '../middleware/auth'
import { sendRenderedPdf } from '../utils/pdfRenderer'
import {
  attendanceRegisterFilename,
  buildAttendanceRegisterHtml,
  normaliseReport,
  type ReportRejection,
} from '../reports/attendanceRegister'

/** One sentence per refusal, written for the person who pressed Download. */
const REJECTION_MESSAGES: Record<ReportRejection, string> = {
  report_missing: 'There was nothing to print. Build the report again and retry.',
  report_too_many_sheets: 'That report has more sections than a single PDF can hold. Export it in two parts.',
  report_no_columns: 'That report has no columns. Pick a date range with at least one record.',
  report_too_many_columns: 'That report has too many columns to print. Narrow the filters and retry.',
  report_too_many_rows: 'That report is too large to print in one go. Choose a shorter date range.',
  report_no_title: 'The report needs a title. Reload the page and retry.',
}

export const exportAttendanceRegisterPdf = async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  const body = (req.body ?? {}) as Record<string, unknown>
  const result = normaliseReport(body)

  if ('error' in result) {
    logger.warn('[attendance/register/pdf] refused', {
      reason: result.error,
      uid: req.user?.uid,
      sheets: Array.isArray(body.sheets) ? body.sheets.length : 0,
    })
    res.status(400).json({ error: result.error, message: REJECTION_MESSAGES[result.error] })
    return
  }

  const doc = result.doc
  const landscape = body.landscape !== false
  const html = buildAttendanceRegisterHtml(doc, { landscape })
  const band = [doc.collegeName, doc.title].filter(Boolean).join(' — ')

  // The header/footer live in Chrome's print options rather than the document so
  // the page numbers are real page numbers, not a guess.
  await sendRenderedPdf(res, html, {
    filename: attendanceRegisterFilename(doc),
    logTag: 'attendance/register/pdf',
    waitUntil: 'load',
    pdf: {
      landscape,
      printBackground: true,
      margin: { top: '16mm', right: '12mm', bottom: '14mm', left: '12mm' },
      displayHeaderFooter: true,
      headerTemplate: `<div style="font-size:8px; width:100%; text-align:center; color:#6b7280; padding:0 12mm;">${escapeForTemplate(band)}</div>`,
      footerTemplate:
        '<div style="font-size:8px; width:100%; text-align:center; color:#6b7280; padding:0 12mm;">' +
        'Page <span class="pageNumber"></span> of <span class="totalPages"></span> · Generated by Vriddhi' +
        '</div>',
    },
  })
}

/** Chrome interpolates this string as HTML; it must never carry user markup. */
function escapeForTemplate(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
